pipeline{
	agent any
	stages{
		stage('CheckOut'){
			steps{
				checkout scm
			}
		}
		stage('Build'){
			steps{
			dir('WebApplication1') {
    bat 'dotnet build WebApplication1.csproj'
}
				
			}
		}
		stage('Publish'){
			steps{
			dir('WebApplication1') {
				bat 'dotnet publish WebApplication1.csproj -o publish'
				}
			}
		}
		stage('Build Docker Image'){
			steps{
			dir('WebApplication1') {
				bat 'docker build -t NiteshKMishra/webapplication1:latest1 .'
				}
			}
		}
		stage('Login to docker hub'){
			steps{
			dir('WebApplication1') {
				bat 'docker login -u NiteshKMishra -p Docker@2024'
				}
			}
		}
		stage('Tag Docker Image'){
			steps{
			dir('WebApplication1') {
				bat 'docker tag NiteshKMishra/webapplication1 NiteshKMishra/webapplication1:latest'
				}
			}
		}
	}
	}