pipeline{
	agent any
	stages{
		stage('CheckOut'){
			steps{
				checkout scm
			}
		}
		stage('Build'){
			steps{
			dir('/WebApplication1/tree/master/WebApplication1') {
    bat 'dotnet build WebApplication1.csproj
}
				
			}
		}
		stage('Publish'){
			steps{
				bat 'dotnet publish WebApplication1.csproj -o publish'
			}
		}
	}
	}